import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const nunito = Nunito({
  subsets: ["latin"],
  variable: '--font-nunito'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LINKS = [{ title: 'Home', href: '/home' },
{ title: 'Nosotros', href: '/about' },
{ title: 'Contacto', href: '/contact' },
{ title: 'Mi Perfil', href: '/my-self' },
{ title: 'Publicar', href: '/posts' }]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${nunito.variable}`} style={{ backgroundColor: "#4A5271" }}>
      <body>
        <Navbar links={LINKS}/>
        {children}
      </body>
    </html>
  )
}