import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";


const nunito = Nunito({
  subsets: ["latin"],
  variable: '--font-nunito'
});

export const metadata = {
  charset: "utf-8",
  title: "PropifyGroup",
  description: "Generated by create next app",
  aplicationName: 'Next.js',
  keyboard: ['Next.js', 'React', 'Javascript'],
  author: [
    { name: 'Jonathan Javier Urquiza' },
    { email: 'jurquiza86@hotmail.com' },
    { https: '//nextjs.org' }
  ],
  publisher: 'Jonathan Javier Urquiza',
  creator: 'Jonathan Javier Urquiza'
};

const LINKS = [{ title: 'Home', href: '/' },
{ title: 'Nosotros', href: '/about' },
{ title: 'Contacto', href: '/contact' },
{ title: 'Mi Perfil', href: '/my-self' },
{ title: 'Publicar', href: '/posts' }]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body>
        <Navbar links={LINKS} />
        {children}
      </body>
    </html>
  )
}